version: '3.4'

services:
  api:
    image: scaffold/api/v1
    build:
      context: .
      dockerfile: WebProject.API/Dockerfile
    ports:
      - 5000:5000
  ui:
    image: scaffold/ui/v1
    build:
      context: WebProject.UI/v1
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    expose:
      - "8080"
