version: '3.4'

services:
  api:
    image: scaffold/api/v1
    build:
      context: .
      dockerfile: WebProject.API/Dockerfile
    networks:
        - scaffold
  ui:
    image: scaffold/ui/v1
    build:
      context: WebProject.UI/v1
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    networks:
        - scaffold
  proxy:
    image: scaffold/proxy/v1
    build:
      context: WebProject.Resources/WebProject.Resources.Nginx
      dockerfile: ./Dockerfile
    networks:
        - scaffold
    ports:
        - "80:80"

networks:
  scaffold:
      driver: bridge