version: '3.4'

services:
  api:
    image: scaffold/api/v1
    build:
      context: .
      dockerfile: WebProject.API/Dockerfile
    ports:
      - 5000:5000
  ui:
    image: scaffold/ui/v1
    build:
      context: WebProject.UI/v1
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "4000:4000"
  proxy:
    network_mode: host
    image: scaffold/proxy/v1
    build:
      context: WebProject.Resources/WebProject.Resources.Nginx
      dockerfile: ./Dockerfile

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
          aux_addresses:
            api: 10.5.0.5
            ui: 10.5.0.6