version: '3.4'

services:
  api:
    image: scaffold/api/v1
    build:
      context: .
      dockerfile: WebProject.API/Dockerfile
    ports:
      - 5000:5000
  ui:
    image: scaffold/api/v1
    build:
      context: .
      dockerfile: WebProject.UI/v1/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:8080
